---
- hosts: gb
  roles:
  - apt
  - helpers
  - xfce-desktop
  - voctomix
  - sidedoor
  - vim
  - grub

- hosts: opi
  roles:
  - fixopi

- hosts: d7212
  roles:
  - devices
  - fix7212
  - wifi

- hosts: bm
  roles:
  - blackmagic

- hosts: docker
  roles:
  - helpers
  - voctomix

- hosts: test
  roles:
  - apt
